### ISSUE TITLE
Unable to open some JPG file

### ISSUE THREAD

**Issue by maximbaz** [karlch/vimiv-qt#141]
I have a weird case:

There are 6 jpg files in the current directory:

```
$ ls -al *.jpg | wc -l
6
```

Here's how `file` sees them:

```
$ file *.jpg
1.jpg: JPEG image data, baseline, precision 8, 1002x1251, components 3
2.jpg: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=12, height=3510, bps=0, PhotometricIntepretation=RGB, orientation=upper-left, width=2550], baseline, precision 8, 1015x1280, components 3
3.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 2339x1696, components 3
4.jpg: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=12, height=1696, bps=0, PhotometricIntepretation=RGB, orientation=upper-left, width=2339], baseline, precision 8, 1339x971, components 3
5.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 2471x1720, components 3
6.jpg: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=12, height=3510, bps=0, PhotometricIntepretation=RGB, orientation=upper-left, width=2550], baseline, precision 8, 1094x1533, components 3
```

I can open all 6 of them using `sxiv` without any issues.

However `vimiv` can only open only `5` of them.

If I just start `vimiv` in the current directory, it shows `5` jpg images, from `2..6` in the list above (`1.jpg` is missing).

If I run `vimiv 2.jpg` it shows me the picture, if I run `vimiv 1.jpg` it opens library mode where again I only see 5 files.

The images are sensitive so I cannot share them with you, however maybe I can assist with debugging in any way?

**Comment by karlch** [comment]
Interesting, my first guess would be that `utils.files.is_image` returns `False`.

You could try:
```
import imghdr
from vimiv.utils import files

print(files.is_image("path/to/unrecognized.jpg"))
print(imghdr.what("/path/to/unrecognized.jpg"))
```

**Comment by maximbaz** [comment]
You are right... But why? 🤔 

```
>>> import imghdr
>>> from vimiv.utils import files
>>> print(files.is_image("/path/to/1.jpg"))
False
>>> print(imghdr.what("/path/to/1.jpg"))
None
```

**Comment by karlch** [comment]
Looking at the implementation of `test_jpeg` in the python `imghdr` module:

```
def test_jpeg(h, f):
    """JPEG data in JFIF or Exif format"""
    if h[6:10] in (b'JFIF', b'Exif'):
        return 'jpeg'
```

When I compare this with the output of `file` you showed before, it seems that is the one image which is in a different format. That would explain the why, now the question is how to solve this. We would more-or-less have to extend this test with a correct sequence of magic bytes for this format, if there is any...

**Comment by maximbaz** [comment]
There must be, as `file` is able to say "JPEG image data"... :)

**Comment by karlch** [comment]
True, do you have access to more of these files so you could compare the first 32 bytes?

**Comment by maximbaz** [comment]
I have found two jpeg files that have this issue:

```                                                                                                      
$ xxd -l 350 1.jpg
00000000: ffd8 ffe1 0950 6874 7470 3a2f 2f6e 732e  .....Phttp://ns.
00000010: 6164 6f62 652e 636f 6d2f 7861 702f 312e  adobe.com/xap/1.
00000020: 302f 003c 3f78 7061 636b 6574 2062 6567  0/.<?xpacket beg
00000030: 696e 3d22 efbb bf22 2069 643d 2257 354d  in="..." id="W5M
00000040: 304d 7043 6568 6948 7a72 6553 7a4e 5463  0MpCehiHzreSzNTc
00000050: 7a6b 6339 6422 3f3e 203c 783a 786d 706d  zkc9d"?> <x:xmpm
00000060: 6574 6120 786d 6c6e 733a 783d 2261 646f  eta xmlns:x="ado
00000070: 6265 3a6e 733a 6d65 7461 2f22 2078 3a78  be:ns:meta/" x:x
00000080: 6d70 746b 3d22 4164 6f62 6520 584d 5020  mptk="Adobe XMP 
00000090: 436f 7265 2035 2e36 2d63 3133 3820 3739  Core 5.6-c138 79
000000a0: 2e31 3539 3832 342c 2032 3031 362f 3039  .159824, 2016/09
000000b0: 2f31 342d 3031 3a30 393a 3031 2020 2020  /14-01:09:01    
000000c0: 2020 2020 223e 203c 7264 663a 5244 4620      "> <rdf:RDF 
000000d0: 786d 6c6e 733a 7264 663d 2268 7474 703a  xmlns:rdf="http:
000000e0: 2f2f 7777 772e 7733 2e6f 7267 2f31 3939  //www.w3.org/199
000000f0: 392f 3032 2f32 322d 7264 662d 7379 6e74  9/02/22-rdf-synt
00000100: 6178 2d6e 7323 223e 203c 7264 663a 4465  ax-ns#"> <rdf:De
00000110: 7363 7269 7074 696f 6e20 7264 663a 6162  scription rdf:ab
00000120: 6f75 743d 2222 2f3e 203c 2f72 6466 3a52  out=""/> </rdf:R
00000130: 4446 3e20 3c2f 783a 786d 706d 6574 613e  DF> </x:xmpmeta>
00000140: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000150: 2020 2020 2020 2020 2020 2020 2020

$ xxd -l 350 2.jpg
00000000: ffd8 ffdb 0043 0006 0405 0605 0406 0605  .....C..........
00000010: 0607 0706 080a 100a 0a09 090a 140e 0f0c  ................
00000020: 1017 1418 1817 1416 161a 1d25 1f1a 1b23  ...........%...#
00000030: 1c16 1620 2c20 2326 2729 2a29 191f 2d30  ... , #&')*)..-0
00000040: 2d28 3025 2829 28ff db00 4301 0707 070a  -(0%()(...C.....
00000050: 080a 130a 0a13 281a 161a 2828 2828 2828  ......(...((((((
00000060: 2828 2828 2828 2828 2828 2828 2828 2828  ((((((((((((((((
00000070: 2828 2828 2828 2828 2828 2828 2828 2828  ((((((((((((((((
00000080: 2828 2828 2828 2828 2828 2828 ffc0 0011  ((((((((((((....
00000090: 0802 a704 0003 0122 0002 1101 0311 01ff  ......."........
000000a0: c400 1d00 0100 0105 0101 0100 0000 0000  ................
000000b0: 0000 0000 0007 0104 0506 0803 0209 ffc4  ................
000000c0: 0055 1000 0103 0202 0406 0e07 0409 0302  .U..............
000000d0: 0603 0000 0102 0304 0506 1112 2131 5507  ............!1U.
000000e0: 1315 9293 b114 1718 3234 3641 5161 7174  ........246AQaqt
000000f0: 8191 b208 1622 3553 7273 3352 94d1 2337  ....."5Srs3R..#7
00000100: 3842 4554 75a1 e124 4362 5683 2528 6382  8BETu..$CbV.%(c.
00000110: c1c2 6465 a2ff c400 1a01 0100 0301 0101  ..de............
00000120: 0000 0000 0000 0000 0000 0001 0203 0405  ................
00000130: 06ff c400 2a11 0100 0103 0205 0402 0301  ....*...........
00000140: 0100 0000 0000 0001 0203 1112 3104 1314  ............1...
00000150: 2151 3233 4152 2271 6162 8123 42ff       !Q23AR"qab.#B.

$ file 1.jpg
1.jpg: JPEG image data, baseline, precision 8, 1002x1251, components 3

$ file 2.jpg
2.jpg: JPEG image data, baseline, precision 8, 1024x679, components 3
```

> Could you try adding ... to the end of `vimiv.utils.files` and see if this helps?

This doesn't help, but just to check that my tests actually worked, I also tried to reduce the condition to simply `return (h[6:10] in (b"JFIF", b"Exif")) or (h[:2] == b"\xff\xd8")` and then `vimiv` was able to show both of these pictures.

**Comment by karlch** [comment]
Thanks for your debugging, this helps a lot. Your reduced condition seems to be the fallback calibre also uses in [their imghdr module](https://github.com/kovidgoyal/calibre/blob/master/src/calibre/utils/imghdr.py). I have patched this up in 7fb3af083a3c10596b79b76385099b13c21f8cac, hope this fixes the issue :smiley:

**Comment by maximbaz** [comment]
Fix confirmed, thank you! We can close the issue, unless you keep them open until the next release.

By the way, I wanted to ask, I noticed we package the old GTK version of `vimiv` for Arch Linux (which was last released in 2017...), do you still consider this QT version unstable / pre-release? Is this why the version is `0.x`? In other words, if an Arch Linux user installs `vimiv` package from official repos, do you as an author want them to get GTK or QT version installed?

**Comment by karlch** [comment]
Perfect! Closing the issue, packaging discussion following.

As I thought that package managers would not like to go down in numbering, and to give some time for stabilizing here, my plan was to replace the Gtk version starting with Qt version `0.10`. Still unsure how to deal with the repositories, but I may rename `vimiv` to `vimiv-gtk` and try to redirect `vimiv` to `vimiv-qt`. A minor release is planned roughly every month, so `0.10` could be around mid-next year.

Reason for not jumping to `0.10` now is that I still break too much on-the-fly currently :laughing:

**Comment by maximbaz** [comment]
I see 😄 I can tell you that from a packager's perspective repository names don't matter that much (we can even put non-github link like https://karlch.github.io/vimiv-qt/ to refer users to your website), but I would recommend you to consider bumping to `1.0` once you feel users should switch from GTK to QT version. From a user perspective, an upgrade from `0.9` to `0.10` is still considered a _minor_ upgrade, they would 100% not expect that underlying code was fully rewritten, especially if this involves some breaking changes.

**Comment by karlch** [comment]
Bumping to `1.0` makes a lot of sense from that perspective, that sounds like a good plan, I will update my notes accordingly, thanks!
