### ISSUE TITLE
add support webp format please

### ISSUE THREAD

**Issue by akimdi** [karlch/vimiv-qt#196]

**Comment by karlch** [comment]
Personally I can open webp images just fine. Seems like qt [relies on system libwep](https://doc.qt.io/qt-5.14/qtimageformats-attribution-libwebp.html) for this usually. On archlinux this is packaged as `libwebp` which is required by `qt5-imageformats`. Do you have something equivalent installed? If not, could you try doing so?

**Comment by akimdi** [comment]
I use ArchLinux too.
I installed these packages but still not opening webp
https://www.archlinux.org/packages/extra/x86_64/libwebp/
https://www.archlinux.org/packages/extra/x86_64/qt5-imageformats/

**Comment by karlch** [comment]
That's unfortunate. Would you mind sharing the output of `vimiv --version` and possibly one file vimiv fails to open, if this is not sensitive information?

**Comment by akimdi** [comment]
version https://termbin.com/2o87

**Comment by akimdi** [comment]
file https://send.firefox.com/download/1b9fff8386f3baae/#7zTzkJ9fuA8mwXqeIy4s1A

**Comment by karlch** [comment]
Perfect, thank you, this makes sense to me now.

It seems like you are using the [gtk version from the official packages](https://github.com/karlch/vimiv), not the newer qt port here. Sorry for the version confusion, I decided a total rewrite was necessary [a while ago](https://github.com/karlch/vimiv/issues/61).

From here on you have two options:
* Switch to the qt port. You have [a stable](https://aur.archlinux.org/packages/vimiv-qt/) and [a development](https://aur.archlinux.org/packages/vimiv-qt-git/) version available in the AUR. This port is still in heavy development but already brings quite a few improvements compared to the initial gtk version. You would have to manually update the config files for any changes you did though.
* Keep the gtk version and install [this AUR package](https://aur.archlinux.org/packages/webp-pixbuf-loader/) for webp support with Gtk. Seems a little bit buggy (Gtk writes a lot of error messages to the terminal), but opens the image fine.

The first option is probably slightly more work but at some point the Gtk version will be deprecated completely anyway. If you need any help switching, of course feel free to open further issues.

**Comment by akimdi** [comment]
Thank you very much.
I will wait until the package appears in the official repositories.
I do not use AUR because it is very unstable.

**Comment by karlch** [comment]
Alright, sounds good to me. I hope to release v1.0 of this port this summer, this would then ideally replace the gtk version also in the official packages. Let's see :smile:

If you don't mind, I would close this issue as soon as I have updated the documentation and AUR packages for the optional `qt5-imageformats` dependency which I was not aware of before.

**Comment by akimdi** [comment]
Yes. Of course.
I wish you all the best and success :+1:
