### ISSUE TITLE
Add customizable sets of metadata information

### ISSUE THREAD

**Issue by karlch** [karlch/vimiv-qt#213]
This could be a follow-up to #212 proposed by @jeanggi90.

The idea is to have a customizable set of metadata information which can be switched easily at runtime. Initial idea was to use `<ctrl>1` to `<ctrl>5`. Personally I would prefer to use `count` directly with the `:metadata` binding, i.e. `1i` to `5i` would toggle between the options, `i` without a `count` would toggle the actual widget. This would be consistent with the slideshow command. What do you think @jeanggi90?

Some hints concerning the implementation:

First we would need the options somewhere, e.g. in the new `metadata` settings class:
```
options = {
    1: "first set of options",
    2: "second set of options"
}
```

Then we would need to populate these with values from the config file in case they are defined. I thought of a new function in `config.configfile` that would somehow iterate over the `METADATA` section, similar to the `_read_plugins` function. How exactly these options are defined is up to discussion. Something simple could be:
```
[METADATA]
0 = first set of options
1 = second set of options
```
which could be parsed quickly by checking if the config key can be converted to an integer.

Finally, the metadata widget in `gui.metadata` would need to know about all this. First of all the `metadata` function which serves as the command would need the `count` argument. Then in the body, a check for `if count is not None` followed by the actual config switching. Something along `api.settings.metadata.keylist.value = api.settings.metadata.options[count]` with proper error checking.

To actually get the changes into the widget, it needs to connect a slot to the setting changed signal. A nice example of this is in `imutils.slideshow` where the slideshow delay is changed according to the setting. All of the logic for setting the metadata text is in the `_update_text` method of the metadata widget where we create and iterate over the `ExifInformation` dictionary updated in #212 . This could probably be re-used / re-factored also for the connected slot.

**Comment by jeanggi90** [comment]
I like you proposition using motions for the shortcut. It make sense to link the *switch set* shortcuts to the *toggle metadata gui* key.

I will have a look what I manage to do and reach out if I need any advice. Thanks a lot for these starter hints!
