### ISSUE TITLE
Display info string if no matching exif keys are found

### ISSUE THREAD

**Issue by karlch** [karlch/vimiv-qt#221]
Currently if there are no exif keys in the image matching the keys the metadata widget is just an empty label. This makes it easy to miss and has caught me by surprise a few times now. It could make sense to add a check along:
```
if exif_information:
# as usual
else:
    self.setText("No matching metadata found")
```
or so.

**Comment by jeanggi90** [comment]
I have actually thought about this as well. I think such a comprehensive text may distract a little to much from the remaining valid metadata and maybe a simple hyphen would be more appropriate. Or to do it right, we could add a boolean setting option to enable/disable this behaviour and leave your proposed text.

**Comment by karlch** [comment]
Ah, this is another option I haven't thought about, but I think we have a little misunderstanding. This only concerns the case if there is no metdata matching the current set at all in the current image. For example, if we are at set 3 and the image does not have `Author` or `Copyright`. Currently this leads to the widget being a little empty blob at the bottom right. This could be improved I think.

**Comment by jeanggi90** [comment]
Yeah I have missunderstood you. I have opened a PR concerning this issue: #225

**Comment by karlch** [comment]
Thanks again for your contribution!
