### ISSUE TITLE
Vimiv produces non-compliant .trashinfo file

### ISSUE THREAD

**Issue by woefe** [karlch/vimiv-qt#240]
According to the [freedesktop trash spec](https://specifications.freedesktop.org/trash-spec/trashspec-latest.html):
1. `DeletionDate` must use the `%Y-%m-%dT%H:%M:%S` format
2. Value of `Path` must be urlescaped (e.g. using `quote`/`unquote` from `urllib.parse`).

However, vimiv uses `%Y%m%dT%H%M%S` and does not escape the `Path` value.

**Comment by karlch** [comment]
I fully agree with 2., this should be done. I don't quite understand 1., the standard says "The date and time are to be in the YYYY-MM-DDThh:mm:ss" but the example is "DeletionDate=20040831T22:32:08". Do you have a file manager to cross-check which format they use?

**Comment by woefe** [comment]
I use https://github.com/andreafrancia/trash-cli, which shows no deletion date on files that were deleted by vimiv. [Relevant Code](https://github.com/andreafrancia/trash-cli/blob/5abecd53e1d84f2a5fd3fc60d2f5d71e518826c5/trashcli/trash.py#L312)

KDE also uses the proper ISO format with dashes: [Code](https://github.com/KDE/kde-runtime/blob/d765545023776ec49ae9bd183176014143fe15d3/kioslave/trash/trashimpl.cpp#L334), [Doc](https://doc.qt.io/qt-5/qt.html#DateFormat-enum)

**Comment by karlch** [comment]
I am convinced, although I find it super weird that the example in the specification is wrong. Should be a very simple fix, thanks for reporting.
