### ISSUE TITLE
Next/Prev Image with persistent zoom level

### ISSUE THREAD

**Issue by jcjgraf** [karlch/vimiv-qt#292]
A handy feature would be if one could go to the next or previous image in the image mode, without the zoom level being set back to default. This is very useful for comparing facial expression, sharpness etc. of multiple similar images.

This functionality could get bound to `Shift + n` and `Shift + p` respectively.

**Comment by karlch** [comment]
I can see how this would be handy, would this also need to keep the "scrolling point" of the image?

I am not completely sure if having this in form of a command or in form of a setting is preferable. Another option could be to have something along `image.keep_zoomlevel`, possibly with a keybinding to toggle it. In any case I would not change the default bindings for `N` and `P` which currently go to the next / previous search result.

**Comment by jcjgraf** [comment]
Yes you are right, the scrolling position should persist too.

I did not mean to replace persisting default bindings. I was just unaware they are already used :smile:

Personally, I do not like a single binary option in the settings to determine the *mode* of the prev/next commands, since I use both behaviours very frequently. I think we are most flexible when we add an additional flag to the `next` command. Depending on if this flag is set, the next image is loaded normally, or with persistent zoom/scroll. This way users can bind whatever mode they wish to their preferred keys. Obviously, we can still quite easily add an additional option in the settings, or as you say an toggle command.

Concerning a possible implementation, the key-points are:
- In `next_path(count:int = 1, preserve:bool = false)` in `vimiv/imutils/filelist` if flag is true, extract the current zoom/scrolling from `vimiv/gui/image`
- After calling `_set_index` and emitting `api.signals.new_image_opened` restore the zoom/scrolling

**Comment by elig0n** [comment]
Could you add an option to automatically use --keep-zoom with next/prev commands via command line and/or config file ?
