### ISSUE TITLE
Toggle manipulate crashes vimiv

### ISSUE THREAD

**Issue by pozitron57** [karlch/vimiv-qt#302]
I installed vimiv-qt on Mac OS (Mojave 10.14.6) via `pip`. When I hit `tm` (toggle manipulate) the program crashes. 

    $ vimiv --version
    vimiv v0.7.0
    Python: 3.9.0
    Qt: 5.15.2
    PyQt: 5.15.2

Also, the program start time is around 3-4 seconds, is it OK?

**Comment by karlch** [comment]
Thanks for the report! The crash should be fixed in the latest master. We hope to release `v0.8.0` sometime soon :tm: in case you want to stick to the `pip` installation. #301 is the last large step-stone until then.

3-4 seconds does sound rather slow, although this is of course somewhat hardware dependent. It takes about 300-700 ms for me.

If you like, you can run this simple script to get an impression of the startup time. I get times around 350 ms for an image of ~2.5 MB.
```python
import timeit


def run(*vimiv_args):
    from vimiv import app, startup
    from vimiv.utils import crash_handler

    args = startup.setup_pre_app(vimiv_args)
    qapp = app.Application()
    crash_handler.CrashHandler(qapp)
    startup.setup_post_app(args)
    qapp.quit()


if __name__ == "__main__":
    path = "/Path/To/Some/Image"
    time = timeit.timeit(f"run('{path}')", globals=globals(), number=1)
    print(f"{time * 1000:.1f}")
```

**Comment by pozitron57** [comment]
Thanks, I installed 0.8.0 and `tm` works properly. By the way, I installed it via
`pip3 install git+https://github.com/karlch/vimiv-qt/`, perhaps it could be advised in the docs.

As for the starting time, your code gives the following output:

```
WARNING  <utils.trie>         s hides longer keys: 'ss', 'sh', 'sl'
qt.qpa.fonts: Populating font family aliases took 1375 ms. Replace uses of missing font family "Mono
space" with one that exists to avoid this cost.
2679.3
```
Once launched, `vimiv` works very fast. I don't think it is hardware issue, other image viewers starts without a noticeable delay.

**Comment by karlch** [comment]
That sounds smart and would certainly make sense to be added to the docs. As it was your idea, would you like to add it to `docs/documentation/install.rst` and open a quick PR? If not, I can just do it later on over the week-end.

Interesting, looks like Mac OS does not provide a `Monospace` font alias out of the box. In case you use the default style, could you replace all occurences of `Monospace` with a font Mac provides in `~/.config/vimiv/styles/default` or whatever the config directory on MAC is? Sorry, I have never really used a Mac in production. This should, according to the log, at least save the 1375 ms to populate the aliases.

Besides this, vimiv will certainly be slower than any image viewers written in say `C` alone due to the import costs. There is certainly more to do, see #124, but I am not sure if there is anything specific that can be done in your case. If you like, you could also send me the profile of the startup code, e.g. by modifying the previous code like this:
```python
def run(*vimiv_args):
    from vimiv import app, startup
    from vimiv.utils import crash_handler

    from vimiv.utils.debug import profile

    with profile():
        args = startup.setup_pre_app(vimiv_args)
        qapp = app.Application()
        crash_handler.CrashHandler(qapp)
        startup.setup_post_app(args)
        qapp.quit()
```

**Comment by pozitron57** [comment]
Unfortunately, I don't feel enough expertise in `pip` to add it to the docs. For example, I am not sure if `--user` flag should be specified in my command.

The preamble of `/Users/<username>/Library/Preferences/vimiv/styles/default` tells that the file is never read, so I created a copy and changed `style=...` in `vimiv.conf`. Now this error mentioning `Monospace` is gone and the program starts tangibly faster, thanks!

The output of the new code is:

```
[13:46:57] WARNING  <utils.trie>         s hides longer keys: 'ss', 'sh', 'sl'
         19544 function calls (19209 primitive calls) in 0.893 seconds

   Ordered by: cumulative time
   List reduced from 844 to 15 due to restriction <15>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.688    0.688 /usr/local/lib/python3.9/site-packages/vimiv/startup.py:79(setup_post_app)
        1    0.000    0.000    0.539    0.539 /usr/local/lib/python3.9/site-packages/vimiv/startup.py:111(init_paths)
        1    0.000    0.000    0.537    0.537 /usr/local/lib/python3.9/site-packages/vimiv/api/__init__.py:57(open_paths)
     10/5    0.001    0.000    0.537    0.107 {method 'emit' of 'PyQt5.QtCore.pyqtBoundSignal' objects}
        1    0.000    0.000    0.532    0.532 /usr/local/lib/python3.9/site-packages/vimiv/imutils/filelist.py:153(_on_load_images)
        1    0.000    0.000    0.532    0.532 /usr/local/lib/python3.9/site-packages/vimiv/imutils/filelist.py:234(_load_single)
        1    0.000    0.000    0.532    0.532 /usr/local/lib/python3.9/site-packages/vimiv/imutils/filelist.py:244(_load_paths)
        1    0.000    0.000    0.530    0.530 /usr/local/lib/python3.9/site-packages/vimiv/imutils/filelist.py:219(_set_index)
        1    0.000    0.000    0.523    0.523 /usr/local/lib/python3.9/site-packages/vimiv/imutils/_file_handler.py:52(_on_new_image_opened)
        1    0.000    0.000    0.522    0.522 /usr/local/lib/python3.9/site-packages/vimiv/imutils/_file_handler.py:91(_load)
        1    0.000    0.000    0.521    0.521 /usr/local/lib/python3.9/site-packages/vimiv/utils/imagereader.py:76(get_pixmap)
        1    0.521    0.521    0.521    0.521 {fromImageReader}
     12/5    0.000    0.000    0.264    0.053 /usr/local/lib/python3.9/site-packages/vimiv/api/objreg.py:54(inside)
        1    0.187    0.187    0.187    0.187 /usr/local/lib/python3.9/site-packages/vimiv/app.py:24(__init__)
        1    0.000    0.000    0.109    0.109 /usr/local/lib/python3.9/site-packages/vimiv/startup.py:123(init_ui)


         19544 function calls (19209 primitive calls) in 0.893 seconds

   Ordered by: internal time
   List reduced from 844 to 15 due to restriction <15>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.521    0.521    0.521    0.521 {fromImageReader}
        1    0.187    0.187    0.187    0.187 /usr/local/lib/python3.9/site-packages/vimiv/app.py:24(__init__)
        1    0.047    0.047    0.047    0.047 /usr/local/lib/python3.9/site-packages/vimiv/gui/commandline.py:50(__init__)
       74    0.033    0.000    0.033    0.000 {method 'connect' of 'PyQt5.QtCore.pyqtBoundSignal' objects}
        1    0.032    0.032    0.032    0.032 {function MainWindow.show at 0x11208c040}
        7    0.015    0.002    0.015    0.002 {built-in method setStyleSheet}
        2    0.008    0.004    0.008    0.004 {built-in method addPath}
        1    0.004    0.004    0.004    0.004 {built-in method _imp.create_dynamic}
        1    0.003    0.003    0.005    0.005 /usr/local/lib/python3.9/site-packages/vimiv/gui/statusbar.py:47(__init__)
        2    0.002    0.001    0.002    0.001 {built-in method waitForDone}
        5    0.002    0.000    0.002    0.000 {built-in method addWidget}
        3    0.002    0.001    0.004    0.001 /usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py:993(_read)
        1    0.001    0.001    0.001    0.001 /usr/local/lib/python3.9/site-packages/vimiv/gui/image.py:68(__init__)
       17    0.001    0.000    0.001    0.000 {built-in method io.open}
       89    0.001    0.000    0.001    0.000 {built-in method posix.stat}


1239.1
```

**Comment by karlch** [comment]
No worries, I quickly added the line. Personally I always use `pip` with `--user` to seperate packages installed via `pip` from packages installed using my package manager, unless in a `venv` of course. But of course I have no clue how this works on Mac OS :smile:

Awesome, thanks for the heads-up. Guess I forgot how my own code works :laughing:

I don't see anything weird in the trace. Most of the time is spent actually reading the image (`fromImageReader`) and creating the Qt application (`app.py:24(__init__)`). From my side I would be happy to close this issue and keep everything else related to the startup performance in the mentioned #124.

**Comment by pozitron57** [comment]
Yes, now the startup time is adequate, thanks a lot.
