### ISSUE TITLE
api.pathlist Inconstiancy

### ISSUE THREAD

**Issue by jcjgraf** [karlch/vimiv-qt#312]
### Problem

While working on BatchMark I have discovered a weird inconsistency then calling `api.pathlist()` from different modes. Depending on whether I am in Thumbnail/Image mode or in Library Mode, the mentioned methods returns a list or a reference to a list (at least it behaves like that).

### Reproduce

Load the following testplugin:
```
from typing import Any

from vimiv import api


class Test:

    @api.objreg.register
    def __init__(self) -> None:
        self.paths = None

    @api.commands.register()
    def test_get(self) -> None:
        self.paths = api.pathlist()
        print(self.paths)

    @api.commands.register()
    def test_print(self) -> None:
        print(self.paths)


def init(*_args: Any, **_kwargs: Any) -> None:
    Test()
```

Assume we have the following directory structure:
```
+-- A
    +-- a1.jpg
+-- B
    +-- b1.jpg
```

- Start vimiv and navigate into `A` using library mode. 
- Switch into thumbnail (or image) mode and run `:test_get`
- Switch batch into library mode and navigate into `B`
- Run `:test_print` and we get `[A/a1.jpg]`

Now we repeat the steps with a slight twist:
- Start vimiv and navigate into `A` using library mode. 
- While in library mode run `:test_get`
- Navigate into `B`
- Run `:test_print` and we get `[B/b1.jpg]`

### Expected Behaviour
I would expect that no matter in which mode I am, `api.pathlist()` returns the list of paths I am currently in as a value and not a reference or something which changes when I change the CWD.

**Comment by karlch** [comment]
Certainly makes sense, should be fixed with a simple additional call to `list`. Let me know if the problem persists for you.

**Comment by jcjgraf** [comment]
That did it, thanks for the quick fix!
