### ISSUE TITLE
Auto-Complete Arguments

### ISSUE THREAD

**Issue by jcjgraf** [karlch/vimiv-qt#320]
Similarly as vimiv completes commands, it would be useful if command arguments would get completed too. This has the advantage that one could easily see what arguments are available without using `:help <command>` and it prevents typos when writing the arguments.

I do not know how complex is would be to add that but I thing it would be great to have that feature.

**Comment by karlch** [comment]
This certainly makes sense and is also part of the completions listed in #6. I remember having a shot at this a while ago and giving up as it was not quite straightforward, but this is certainly still something that would be great to have :blush:

If you don't mind, I would close this issue in favour of #6.

**Comment by jcjgraf** [comment]
Oh gosh, I should have rather scrolled down the issue list instead of using the search functionality :see_no_evil: That is exactly what I meant.
