### ISSUE TITLE
Crash on Write with Tilde

### ISSUE THREAD

**Issue by jcjgraf** [karlch/vimiv-qt#337]
Writing an image to a path with leading tilde (i.e. `:write ~/Downloads/test.jpg`) causes vimiv to crash with a `FileNotFound` error. I have not looked into it but it seems like the tilde does not get expanded correctly.

**Comment by karlch** [comment]
Makes perfect sense and should be fixed with e5ce3a4f255cdf461219b6b34c8925174f787c6c. Thanks for pointing this out!
