### ISSUE TITLE
Support for .avif format

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [karlch/vimiv-qt#338]
Hi!

I recently discovered a new image format: AVIF.

There is a libavif in most distribution repositories, however installing it on Arch Linux did not allow me to open the following file:
https://linkmauve.fr/files/railgun.avif

Support for this would be nice. ;)

Thanks again for your software.

**Comment by schyzophrene-asynchrone** [comment]
As for the previous issue I opened, if you indicate to me what I should do, I can take care of it. It may take a while, but I guess no one is in a hurry regarding this.

**Comment by karlch** [comment]
Hi!

Thanks for reporting this! I found [this qt imageformats plugin](https://aur.archlinux.org/packages/qt-avif-image-plugin-libavif-git/) which should make it possible for qt to read and write avif files. Unfortunately avif is not recognized by [imghdr](https://docs.python.org/3/library/imghdr.html) which we use to identify the image type of any file.

The easiest way forward should be to:
- install the AUR plugin
- add a test that identifies if a file is of type `avif`

We already have `vimiv/plugins/imageformats.py` to handle this usecase so it should be fairly straightforward to add a test similar to the one we have for `cr2`, as long as one can identify `avif` files using the bytes header.

Hope this helps! Let me know if there is anything I can help with :blush:
