### ISSUE TITLE
Bind <return> in keys.conf

### ISSUE THREAD

**Issue by petobens** [karlch/vimiv-qt#34]
See https://github.com/karlch/vimiv/issues/75

**Comment by karlch** [comment]
Does `<return> : open-selected --close` work for you?

**Comment by petobens** [comment]
Yep, does work. Sorry about the noise.

**Comment by petobens** [comment]
One last question regarding bindings: how can I map `dd` to `delete %` (i.e I want to have `dd` behave as `x`)?. Thanks

**Comment by karlch** [comment]
No worries, that's what issues are for :smile:

Does mapping `dd : delete %%` work as expected? Note that the `%` character has to be escaped, as it is treated specially by python.

Do you have any suggestions on how to improve the documentation?

**Comment by petobens** [comment]
Escaping `%` works! Thanks. Mmm everything seems to work pretty smoothly so far and is pretty well documented (I love the fact that we can now set our own style).
