### ISSUE TITLE
Using pattern matching in keybindings on files with whitespaces

### ISSUE THREAD

**Issue by sadsumi** [karlch/vimiv-qt#355]
This might be a bug.

I have the following keybindings in `keys.conf`:
```
Tc : command --text='!file-tools %%'
Tm : command --text='!file-tools %%m'
```
I use them to run some external script on selected files. It works as intended - when I hit, say `Tc`, vimiv enters command line mode and replaces `%%` with the current filename, then I hit enter to execute the command. However, if filename contains a whitespace (say `file name.png`), it fails to enter the command line and prints:

```
command: Unrecognized arguments: name.png
```
I believe there is something wrong with `%` substitution from `command --text` binding because if I type `:!file-tools %` manually, it works fine.

**Comment by karlch** [comment]
Thanks for the report!

What is happening is that it replaces the `%%` with the current file when executing the keybinding. In case there are any whitespaces, e.g. `path with space.png`, this gets escaped to `'path with space.png'`. Putting this together with the command we end up with `command --text='!file-tools 'path with space.png''` which is then invalid as the quotes already close when the escaped path starts.

Knowing this we should be able to fix this by binding in the form of:
- `Tc : command --text='!file-tools \%%'` to delay path substitution to when the actual `file-tools` command is executed.
- `Tc : command --text="!file-tools %%"` so we do not make use of the single quotes twice.

I am not sure if we want to enter the hassle of detecting possibly conflicting quotes for keybindings / commands, but if it is simple enough to do, this would be certainly be nice to have.

Hope this helps! :blush:

**Comment by sadsumi** [comment]
Ah, I see, thanks for response. I changed `'` to `"` and it works indeed. I think this is surely a rare edge case so it's probably not worth getting around this in code. However, it would be nice to have at least a note in docs, possibly in the keybindings section, to point out how `%%` gets escaped in case of whitespaces. Or that you can delay path substitution in general. Correct me if I'm wrong but I couldn't find it.

**Comment by karlch** [comment]
This certainly makes sense, I added a note recommending double quotes for keybindings that involve `%` to the corresponding note in the [documentation](https://karlch.github.io/vimiv-qt/documentation/configuration/keybindings.html).
