### ISSUE TITLE
Is it possible to save the contents of an image to the clipboard?

### ISSUE THREAD

**Issue by pglira** [karlch/vimiv-qt#358]
Often it would be useful to copy the contents of an image in order to paste it, e.g. in Teams, WhatsApp, LibreOffice, ... I haven't found an option/command for this. Can it be added via config?

**Comment by jcjgraf** [comment]
There is not such functionality in vimiv yet. But in #359 I have added the command `copy-image` which should do what you are asking for. It would be great if you could have a look at it and check if it works and does what you want.

**Comment by pglira** [comment]
Thanks!

I've installed the new version and can see the new options.

However, it seems that it is not always working. So far I haven't found out if it is related to the image format (png, jpg, bmp) or to the target program, e.g. I can paste the image often in libre office writer, but almost never in whatsapp web.

**Comment by jcjgraf** [comment]
A more extensive tests confirms your findings that not all images and all target programs works equally well.

I think it is mainly related to the target program and file size. It seems like some programs are not able to handle images larger than some size. For me, copying to Libre Office Write works for all jpgs of any size (tested up to 8 MB), while Element (Riot) only seems to allow pasting images smaller than 1MB. I could imagine that the threshold for web applications may be even lower.
Currently, I do not have any other image formats available, but I think this should generally works for all file types which vimiv supports out of the box (it certainly does not work for CR2 yet).

Could you try to confirm these findings by e.g. trying to copy rather small images to whatsapp web? Do you have an other application which allows copy/pasting images? If so, are there images which you can copy/paste to Whatsapp Web from the other application but not for vimiv?

**Comment by karlch** [comment]
Just merged #359 which implements this along with an option to reduce the image size before copying. All credit goes to @jcjgraf, thanks a lot for working on this!

@pglira let us know if you encounter further issues / have other ideas for improvement :blush:
