### ISSUE TITLE
Permanent deletion

### ISSUE THREAD

**Issue by wedens** [karlch/vimiv-qt#361]
I don't really use trash and I'd like to be able to permanently delete images. Default `:delete` command (bound to `x`) moves images to trash and I don't see a way to change this behavior.

Is it possible to somehow configure vimiv-qt so that `x` actually deletes a file? If not, perhaps there could be a new command or an argument to `:delete` command for that?

**Comment by karlch** [comment]
Thanks for your interest in vimiv!

One quick solution would be to use `:!rm` and pass this on to the shell. I was actually considering to implement some of the shell commands that are used often using the python os-related modules and exposing them, ones that come to my mind are for example:
- `:rm`
- `:mv`
- `:mkdir`

but I am not yet sure if this would be worth the extra code compared to just using `:!cmd` accordingly.

**Comment by wedens** [comment]
Thanks for the suggestion. I think binding `x : !rm %` should do the job. I've noticed that `:delete` is bound as `x : delete %%` in keys.conf. What's the difference between  one and two `%` signs? Does `%` (or `%%`) handle path escaping when it expands?

**Comment by wedens** [comment]
Got it. Thanks! This solution is good enough for me.
