### ISSUE TITLE
Organizing images

### ISSUE THREAD

**Issue by se7en-x230** [karlch/vimiv-qt#366]
How would I cp/mv images to different folder? 
Can I mark several images and cp/mv them as I can bulk rename?

Also it doesn't change anything if I set the size 400 or 1  in the Thumbnail section of the vimiv.conf.
It is as if this section of the config file is not read.
SOLVED ... 512 is the highest

**Comment by karlch** [comment]
Thanks for your interest in vimiv!

Currently the way to cp/mv images is to pass the command to the shell, e.g.
```
:!mv my_image.jpg ~/whatever/new_name.jpg
```

To refer to the marked images you can use the `%m` wildcard, e.g.
```
:!cp %m ~/other/folder/
```

Hope this helps! :blush:

**Comment by se7en-x230** [comment]
Thanks for the fast response. 

Is there a collection of aliases that people use?

I am currently using sxiv but I love vimiv.

**Comment by jcjgraf** [comment]
>Also it doesn't change anything if I set the size 400 or 1 in the Thumbnail section of the vimiv.conf.

This option sets the default zoom value of the thumbnail view. It can be any value of `64, 128, 256, 512`

In addition to what @karlch has already said, there is is the glob `%` which matches the current image. So you can write
```
:!mv % ~/whatever/new_name.jpg
```
instead of
```
:!mv my_image.jpg ~/whatever/new_name.jpg
```

I do not want to make any advertises, but when you have to mark many consecutive images, the plugin [BatchMark](https://github.com/jcjgraf/BatchMark) may come in handy :blush:

**Comment by karlch** [comment]
I don't really know of a collection of aliases, but you can of course create a whole bunch of them in your `~/.config/vimiv/vimiv.conf` in the alias section. Mine is currently rather empty :laughing: 
```
[ALIASES]
background = !hsetroot -cover %%
```

It could be nice to have a collection of aliases in some central place where anyone can add their favourite ones with some explanation :thinking:

**Comment by se7en-x230** [comment]
> I do not want to make any advertises, but when you have to mark many consecutive images, the plugin [BatchMark](https://github.com/jcjgraf/BatchMark) may come in handy

That is a nice plugin. 
I remapped the "mark" m key to s as it is faster to hit jsjsjs as njnjnj ... :) 
I I tried to combine the mark with the j or p key next but I think there is no way to combine 2 commands?

**Comment by jcjgraf** [comment]
I am glad you like it :blush:

You can actually combine multiple commands in a mapping. Here an example for marking and going to the next image:
```
<alt>m: mark %% && next
```

**Comment by se7en-x230** [comment]
Wow that's so cool 

Yes loving vimiv

**Comment by se7en-x230** [comment]
best I could come up with is an alias.
alias = !cp %m 
This way I can mark images and run 
:cp /Destination_Folder

not perfect but a bit faster..

**Comment by se7en-x230** [comment]
Only thing I can't figure out is how to unmark the copied items.
!cp %m && mark %m 
doesn't work. Meaning I have to go back an manually unmark them...

https://filedn.com/lqcjyrwcp7w7bppJCRFOvPB/vimiv.mp4

**Comment by jcjgraf** [comment]
Run `:mark-clear` after copying them

**Comment by se7en-x230** [comment]
cp = !cp %n && mark-clear 
give me an error: External command /usr/bin/cp ... target ... last picture is not a directory

**Comment by se7en-x230** [comment]
Yes that was my guess that the && will assume that the next command is still a shell command. Thanks anyway. 
Really enjoy vimiv

**Comment by jcjgraf** [comment]
I was wrong. Using `&&` you can actually combine shell and vimiv commands. I.e. `cp = !cp %m /tmp && mark-clear` works for me. But your problem is that you are missing the second argument to `cp`.

**Comment by se7en-x230** [comment]
ERROR    <vimiv>              mark-clear: Unrecognized arguments: .
Yes you are correct ... just found out that the . or path is piped into the second command as well...

**Comment by karlch** [comment]
I assume you are looking for something along the lines of
```
!cp %m $DIR && mark-clear
```
where you want to define `$DIR` later on?

Aliases are unfortunately not this powerful, they are simple string replacements.

You could however write your own little plugin, let's call it `mycp` and create the python file `~/.local/share/vimiv/plugins/mycp.py` with the following content
```python
import os
import shutil

from vimiv import api


@api.commands.register()
def copy_marked(target: str):
    """Copy all marked images to target."""
    target = os.path.abspath(os.path.expanduser(target))
    if not os.path.isdir(target):
        raise api.commands.CommandError("target must be a directory")

    for src in api.mark.paths:
        shutil.copy(src, target)
```
to create a new `:copy-marked` command that takes one argument, the target directory.

and update your plugins section in your `vimiv.conf` to include your newly created plugih
```
[PLUGINS]
mycp =
...
```

Does this achieve what you would like or was I over-interpreting? :smile:

**Comment by se7en-x230** [comment]
Thanks for your fast response and thanks for your help.
Yes that is correct but more work (for you) than I was hoping for.

I created the plugin and added mycp = to vimiv.conf 
The command is in the list, copies but doesn't deselect the marked pictures.

**Comment by karlch** [comment]
I agree that this is of course more effort than just writing an alias, but having it in python gives us all the flexibility :blush: 

To clear the mark in addition, just add
```python
    ...
    for src in api.mark.paths:
        shutil.copy(src, target)

    api.mark.mark_clear()
```

**Comment by se7en-x230** [comment]
AMAZING ... 
Created a mymv.py same template with the move command as well ... 
Looks like I am set and my new image viewer/manager is vimiv 

https://filedn.com/lqcjyrwcp7w7bppJCRFOvPB/vimiv-plugin.mp4

Thank you so much for your help

**Comment by karlch** [comment]
Awesome, glad you like it :tada: Nice setup you got there!

Note that you can pack more than one command function into the same plugin .py file, there is no restriction to have a single one per file, but the organization is up to you of course.

Happy to help! Closing this for now, feel free to re-open / continue asking questions here as needed :blush:
