### ISSUE TITLE
Move between thumbnail and library view

### ISSUE THREAD

**Issue by se7en-x230** [karlch/vimiv-qt#367]
Once in thumbnail view I can't navigate to other folder anymore without tl off/on.
Am I missing some shortcut? 
I helped myself with a alias 
tb = toggle library && toggle library

Is there a away to start in thumbnail via or run this alias at startup?

**Comment by karlch** [comment]
The easiest way to just enter the library instead of toggling it is using `gl`, i.e. `:enter library`. Does this already achieve what you like?

If you want to run an arbitrary command upon startup, you can pass it on the command line. The one I find myself using most often is
```bash
vimiv * --command fullscreen
```
but you could also do something to have thumbnail mode open and enter the library directly
```bash
vimiv * --command "enter thumbnail" --command "enter library"
```

**Comment by se7en-x230** [comment]
Nice that is exactly what I need as a the default.

Thanks

**Comment by karlch** [comment]
I am not quite sure I understand. Care to explain what you mean with "as the default"?

**Comment by se7en-x230** [comment]
I set an alias for vimiv="vimiv * --command "enter thumbnail" --command "enter library"" as I like that view to be my default browsing/working view.

**Comment by karlch** [comment]
I see, sounds good :+1: Although you are then no longer able to select an individual image to start off with, right?

**Comment by se7en-x230** [comment]
Yes that is the downside. I would have to use the full path /usr/bin/vimiv 0220.jpg ...

**Comment by karlch** [comment]
I am not sure if there is anything vimiv could do here. You could of course define a shell function, or use a different alias for the two cases. Do you think there is anything left on the vimiv side where we could help?

**Comment by se7en-x230** [comment]
No I am super happy with my setup. Vimiv is my default image    viewer.
The cp/mv/rename feature turns it into a image manager and not "only"  a simple image viewer.

Enjoying your software. Thank you.

**Comment by karlch** [comment]
I will go ahead and close this one as well then, let us know if there is more we can do :blush:
