### ISSUE TITLE
[Feature] Add view (read-only) mode

### ISSUE THREAD

**Issue by willemw12** [karlch/vimiv-qt#368]
It would be nice to have a view mode (read-only mode) and not have to worry about accidental overwriting of files during that vimiv session.

In view mode, all commands that change or (re)move an image (buffer) are disabled.

To run in view mode, run: `vimiv -R`. It is not necessary, or maybe not even desired, to have it as a config setting.

As an alternative to view mode, one can remove the mappings in the keyfile that change or (re)move images.

**Comment by karlch** [comment]
Thanks for opening an issue on github!

This sounds do-able, I will look into it :blush:

**Comment by karlch** [comment]
Implemented in #369.

**Comment by willemw12** [comment]
Vim appends " [RO]" to the filename on the status line when in view mode. Maybe vimiv can do the same. Or append " [RO]" to the mode on the status line.

**Comment by karlch** [comment]
This makes a lot of sense. I went ahead and added a corresponding status module in 4124df891ca9bc14a0dfab4724567e8366c46565. Let me know if this works as expected :blush: 

Note that you probably have to update your `vimiv.conf` as described in the [changelog](https://karlch.github.io/vimiv-qt/changelog.html).

**Comment by willemw12** [comment]
It all works correctly.
