### ISSUE TITLE
Add keybinding to toggle hidden files

### ISSUE THREAD

**Issue by karlch** [karlch/vimiv-qt#372]
This was initially requested in the deprecated gtk port [here](https://github.com/karlch/vimiv/issues/94).

Personally I would prefer to follow ranger's binding scheme and bind `set library.show_hidden!` to `zh`. As we don't have any bindings starting with `z` yet, this could just be added to the defaults no problem at all.

**Comment by Kakupakat** [comment]
Sorry for the noise on the site of the deprecated gtk port. I actually use the qt version.

If you would like to add the keybinding to ` zh `, I think that is OK. 

Is there a way to change the bindings in the config file?

**Comment by jcjgraf** [comment]
> Is there a way to change the bindings in the config file?

All bindings can be changed in the `keys.conf` file. See [here](https://karlch.github.io/vimiv-qt/documentation/configuration/keybindings.html) for more information

**Comment by karlch** [comment]
I have added the keybinding in 783ba9e474e30a471403df5427ce10147a94c447 along with a small update in how the selection behaves when toggling hidden files in 91ad6ed9bf890e9619afd9e749651ec4c8bb1d7d. Let us know if you have any issues customizing the keybindings or more ideas for new features :blush:
