### ISSUE TITLE
Printing marked images to stdout

### ISSUE THREAD

**Issue by loiccoyle** [karlch/vimiv-qt#379]
Is there a way to print the marked images to stdout similar to `sxiv`? I would like to use `vimiv` in some scripts.

**Comment by jcjgraf** [comment]
Thanks for your interest in vimiv!

I can see the power of such a command, but as far as I know there is not such functionality yet. I quickly went forward and added the command `:mark-print` in #380. Would you mind to check it out and tell us if it fulfils your requirements?

I do not think that you are looking for that, but you can also launch shell scripts from within vimiv and pass a list of all marked images as augments to the script. The syntax is the following: `:!myScript %m`. For full documentation see [here](https://karlch.github.io/vimiv-qt/documentation/getting_started.html#command-line).

**Comment by loiccoyle** [comment]
Ideally I would like to be able to do something like: 
```sh
SELECTED_PICTURE="$(find pictures/ -type f | vimiv)"
```
Where `vimiv` opens up in thumbnail mode, I can then select a single or multiple images, when I quit the marked images are printed to stdout.

`sxiv` handles this usecase with launch arguments, [see man page](https://www.mankier.com/1/sxiv): 
```sh
SELECTED_PICTURE="$(find pictures/ -type f | sxiv -tio)"
```

Maybe something similar could be implemented in `vimiv`?

**Comment by karlch** [comment]
In principle this should be doable after we merge #380 with a workflow along:
```bash
SELECTED="$(vimiv $(find pictures -type f) --command 'enter thumbnail'))"
```
and running the command defined in the PR before closing vimiv. This could of course be simplified / shortened by defining aliases or keybindings accordingly. Is this going in the right direction?

Personally I have found running scripts from vimiv and passing the marked images as described by @jcjgraf the easier workflow. Everything more complicated I like solving using a dedicated [plugin in python](https://karlch.github.io/vimiv-qt/documentation/configuration/plugins.html).

**Comment by jcjgraf** [comment]
> Personally I have found running scripts from vimiv and passing the marked images as described by @jcjgraf the easier workflow.

While I agree with that, the workflow @loiccoyle  is describing is in essence *rofi for images*. And I think that is especially powerful if is is nicely and easily usable from within shell scripts.

**Comment by loiccoyle** [comment]
> While I agree with that, the workflow @loiccoyle is describing is in essence _rofi for images_. And I think that is especially powerful if is is nicely and easily usable from within shell scripts.

Yes exactly !

I quickly looked into the plugins and I found a potential solution, simply adding the following plugin:
```python
from vimiv import api

def cleanup(*args, **kwargs):
    if api.mark._marked:
        print('\n'.join(api.mark._marked))
```

But using a plugin might be kinda awkward because toggling this behaviour is more involved and maybe you would want this built into `vimiv` and controlled through launch arguments a la `sxiv` ?

**Comment by loiccoyle** [comment]
Thanks a lot for the switch replies and PR, I appreciate it and I look forward to using `vimiv`!
I'm closing this issue.
