### ISSUE TITLE
Setting WM_CLASS or WM_CLASS_INSTANCE

### ISSUE THREAD

**Issue by loiccoyle** [karlch/vimiv-qt#384]
Hi ! Me again !

I use a tilling window manager (`bspwm`) and I would like to be able to set a rule such as:
```sh
bspc rule -a vimiv:float state=floating
```

To automatically set some `vimiv` instances to floating, typically when launching `vimiv` from a script to kind of emulate a `rofi` popup.

I saw that I can change the title through:

`vimiv --set title.fallback float`

But with `bspwm` (as far as I can tell) it isn't too easy to set a rule based on a title and it feels a bit hacky.

Ideally I would like to be able to change the WM_CLASS or WM_CLASS_INSTANCE of `vimiv`.

`sxiv` does allow this through the `-N` argument.

I quickly had a look at how to go about doing this with `pyqt5`, but I couldn't find a way acheive it but I have little experience with `pyqt5`.

**Comment by jcjgraf** [comment]
I am not using bspwm, but apparently since `0.9.10` is allows to match for the window name using `-name`. Have you tried that?

**Comment by karlch** [comment]
For reference, setting WM_CLASS_INSTANCE should be rather simple by passing the correct flags to the constructor of `QApplication`. Random example in `vimiv.app`:
```python
    @api.objreg.register
    def __init__(self) -> None:
        """Initialize the main Qt application."""
        super().__init__([vimiv.__name__, "--name", "floating"])
```

In principle we could add a setting for this, or we could allow passing arbitrary arguments to qt like [qutebrowser](https://github.com/qutebrowser/qutebrowser) does via `--qt-arg name value`.

**Comment by loiccoyle** [comment]
> I am not using bspwm, but apparently since `0.9.10` is allows to match for the window name using `-name`. Have you tried that?

The `-name` argument in the reddit post is for applications to change the WM_INSTANCE_NAME not for `bspwm` rules, which is what I'm describing.

And I can't seem to get `bspwm` to match on the WM_NAME I could be doing something wrong, I'll keep trying.

For reference I found a similar discussion regarding this for `qutebrowser`: https://github.com/qutebrowser/qutebrowser/issues/514

**Comment by karlch** [comment]
As we spawn a completely new process everytime vimiv is launched, I don't see us being affected too much by the fact that this has to be defined once upon startup. We don't really have the concept, and I doubt we ever will (don't quote me on this :smile:), of multiple windows within one "session".

**Comment by jcjgraf** [comment]
> and I doubt we ever will (don't quote me on this :smile:), of multiple windows within one "session".

Ui, this statements reminds my of a feature request I once wanted to open; Support for multiple monitors :upside_down_face: :see_no_evil:
