### ISSUE TITLE
[Question] How to sort the library?

### ISSUE THREAD

**Issue by TornaxO7** [karlch/vimiv-qt#386]
In my current directory I have files numbered from 1 to 16. If I open vimiv and than the library by pressing `tl` I'm getting this:

![image](https://user-images.githubusercontent.com/50843046/116938137-8ef71380-ac6a-11eb-9491-b8240b5b4f52.png)

How can I sort the names from 1 to 16 instead of `1.jpg` than `10.jpg` (instead of `2.jpg`)? I've tried to type `:sort` but this command doesn't exist.

**Comment by se7en-x230** [comment]
I avoid this problem always by renaming the files starting with 0001.png...
You can bulk rename with vimiv and it does exactly that

**Comment by TornaxO7** [comment]
Hm... ok, I'm not that satisfied with this "trick", but I think that's fine. Could be a feature for the future ;)

**Comment by jcjgraf** [comment]
Vimiv has currently no option or command no change the ordering of the images. Images are listed according to the order given by `sorted` which order string lexicographically. I.e. `"1.jpg"` comes before `"2.jpg"` which comes before `"9.jpg"`. But since `"1"` comes before `"2"`, `"10.jpg"` comes before `"2.jpg"`.

There is an open issue #75 concerning the improvement/extend the ordering. Also, some efforts have already been applied on this in #76, tough it has unfortunately never been finished...

**Comment by jcjgraf** [comment]
I went forward and started working on #75 in #387. I have added two setting options, `image_order` and `directory_order` to change the image order and directory order respectively. Beside others, I have added the order `name-natural` which should suit your needs. You your @TornaxO7  whichly check if it indeed does so? Once you are in the correct branch, you can set the order using `:set image_order name-natural`.

**Comment by TornaxO7** [comment]
I'm sorry for the very late reply! Could you explain me which branch I should use?

**Comment by TornaxO7** [comment]
Oh wait, I just found [your pull request with the given branch](https://github.com/karlch/vimiv-qt/pull/387)

**Comment by TornaxO7** [comment]
Hm... ok, so all I need to do is
1. `git clone git@github.com:jcjgraf/vimiv-qt.git`
2. `cp misc/Makefile .`
3. `sudo make install` (and remove the original `vimiv-qt` from my package manager first)
4. use `vimiv`
right?

**Comment by jcjgraf** [comment]
Hey, no worries for the delay, I have not worked on this PR for some time too...

There is no need to clone my fork of vimiv and replace you system-wide vimiv installation. Instead follow these steps:

- Clone vimiv repo: `git clone https://github.com/karlch/vimiv-qt.git`
- Enter local repo: `cd vimiv-qt`
- Pull my PR and enter branch: `git fetch origin pull/387/head:ImageOrder && git checkout ImageOrder`
- Edit the vimiv configuration (probably located in `.config/vimiv/vimiv.conf`) and add `image_order = natural` to the end of the section `[GENERAL]`
- Start vimiv: `.venv/bin/vimiv` (you must be inside the local repo clone)

Do not hesitate to comment if something is not working. I have not run every command, so I may have missed something :upside_down_face:

**Comment by TornaxO7** [comment]
Ok, so I tried it out and it seems to work. Thank you!

**Comment by jcjgraf** [comment]
Awesome, thanks for testing. I hope that I can finish this PR soon.
