### ISSUE TITLE
Large GIF size would make GIF seems like cropped

### ISSUE THREAD

**Issue by Incests** [karlch/vimiv-qt#414]
Viewing 125 MB gif would make it seems like cropped.
```
vimiv v0.8.0

Python: 3.9.6
Qt: 5.15.2
PyQt: 5.15.4

Svg Support: True
Pyexiv2: None
Piexif: None
```

![](https://fs-01.cyberdrop.cc/nicememe.TUESIz4GSJ2B3fvCpqG-BDL0mPcT.png)

The animation still playing smoothly, no issue.
[GIF File](https://img-01.cyberdrop.to/Proyek_Baru_37_[77356FD]-raRFSW6P.gif)

**Comment by karlch** [comment]
Thanks for your report!

Unfortunately I cannot reproduce this out of the box, works just fine on my laptop using the gif you linked.

I will see if I can do some more digging on the week-end to check what could be different on our side, version should be the same (I tried both v0.8.0 and the latest master).

![scrot-2021-08-19_18:04:04](https://user-images.githubusercontent.com/12006766/130103846-a701af64-5231-4525-b925-8e936c4c6e10.png)

**Comment by asrcpq** [comment]
Hi, I've just got the same problem. I don't know much about Qt and PyQt, but it seems that it is caused by `setMovie` not resizing the QLabel:

https://github.com/karlch/vimiv-qt/blob/b4b7772f414fec9448a1faa716af73e7eeba4731/vimiv/gui/image.py#L124-L126

When I add `widget.resize(movie.currentPixmap().size())` here, the whole image is displayed.

**Comment by karlch** [comment]
Thanks for your effort on debugging this!

Funky, I am still not able to reproduce, when adding a little debug statement:
```python
        widget = QLabel()
        widget.setMovie(movie)
        self._update_scene(widget, QRectF(movie.currentPixmap().rect()), keep_zoom)
        print(widget.size(), movie.currentPixmap().size())
```
I properly get
```
PyQt5.QtCore.QSize(2560, 1440) PyQt5.QtCore.QSize(2560, 1440)
```

However, I see no harm adding the call to `widget.resize` if this fixes the issue for you. The resize is near-instant when it does not have to do anything. Would you @asrcpq like to open a quick PR adding yourself to the contributors? If not, I can also just fix this later.

**Comment by asrcpq** [comment]
I think you can just fix it since I am not really a user of this project. I was writing my own image viewer and noticed the same problem. I guess it should be related to the window manager behavior of resizing/rendering order, because I get this problem in i3wm but not in icewm.
