### ISSUE TITLE
vimiv: gdk_pixbuf_gif_anim_iter_get_pixbuf(): python3.9 killed by SIGSEGV

### ISSUE THREAD

**Issue by sanjayankur31** [karlch/vimiv-qt#415]
Reporting a downstream bug:

https://bugzilla.redhat.com/show_bug.cgi?id=1995944

Description of problem:
I opened the attached file.

Version-Release number of selected component:
vimiv-0.9.1-17.fc34

Additional info:
reporter:       libreport-2.15.2
backtrace_rating: 4
cgroup:         0::/user.slice/user-1000.slice/user@1000.service/app.slice/app-glib-vimiv-13204.scope
cmdline:        /usr/bin/python3 -s /usr/bin/vimiv --start-from-desktop /home/miketal/.cache/astroid/6e1yll7esx-image001.gif
crash_function: gdk_pixbuf_gif_anim_iter_get_pixbuf
dso_list:       /usr/bin/python3.9 python3-3.9.6-2.fc34.x86_64 (Fedora Project) 1627213604
executable:     /usr/bin/python3.9
journald_cursor: s=b0f9572d83cb4398ade090a7fa8c987f;i=b2856;b=47d7a5f3d7c144e7ba5a710ce5986d88;m=2762a046;t=5c9f83db1d2fb;x=d0cade682f68f6ef
kernel:         5.13.10-200.fc34.x86_64
rootdir:        /
runlevel:       N 5
type:           CCpp
uid:            1000

Truncated backtrace:
``` trace
Thread no. 1 (10 frames)
 #0 gdk_pixbuf_gif_anim_iter_get_pixbuf at ../gdk-pixbuf/io-gif-animation.c:436
 #1 ffi_call_unix64 at ../src/x86/unix64.S:76
 #2 ffi_call at ../src/x86/ffi64.c:525
 #3 pygi_invoke_c_callable at ../gi/pygi-invoke.c:684
 #4 pygi_function_cache_invoke at ../gi/pygi-cache.c:862
 #5 pygi_callable_info_invoke at ../gi/pygi-invoke.c:727
 #6 _wrap_g_callable_info_invoke at ../gi/pygi-invoke.c:764
 #7 _callable_info_call at ../gi/pygi-info.c:548
 #8 _PyObject_MakeTpCall at /usr/src/debug/python3.9-3.9.6-2.fc34.x86_64/Objects/call.c:191
 #9 _PyObject_VectorcallTstate at /usr/src/debug/python3.9-3.9.6-2.fc34.x86_64/Include/cpython/abstract.h:116
```

This is the file that caused the crash:

![image001](https://user-images.githubusercontent.com/102575/130217276-4c6f0c40-bc31-4f16-b2fb-e68cec4ead46.gif)

Note: I downloaded the file and when I opened it with vimiv I did not see a crash. So I'm not quite sure what's causing it. (hence reporting it here :D)

The downstream bug has more attachements that may be useful too.

**Comment by jcjgraf** [comment]
I guess you are confusing the deprecated [vimiv](https://github.com/karlch/vimiv) with vimiv-qt. `gdk_pixbuf_gif_anim_iter_get_pixbuf` looks like a GTK function, but here we are using QT.

We are aware of the confusing situation with the GTK and QT version and are glanning to resolve it once version 1.0 gets released...

**Comment by sanjayankur31** [comment]
Ah, silly me. No wonder I wasn't able to reproduce it. I've all but forgotten about vimiv-gtk. I'll follow up on the Fedora bug and ask the user to move to vimiv-qt. Thanks. Closing this now.
