### ISSUE TITLE
Feature request: support more image format.

### ISSUE THREAD

**Issue by szsdk** [karlch/vimiv-qt#418]
Do you have any plan to support more image format like jp2, tiff?

**Comment by jcjgraf** [comment]
Hey @szsdk, thank you very much for your request. While we have not planned to support these file types, if there is demand for it and it is not too hard to implement them, we can certainly add them. 

A quick [research](https://doc.qt.io/qt-5/qtimageformats-index.html) shows that these types are more or less directly supported by QT and hence, it is probably not to hard to add them.

**Comment by szsdk** [comment]
Yeah, these two formats occur occasionally in my daily usage. I'd like to use vimiv to view them. I am so addicted to vim binding :).

**Comment by karlch** [comment]
Tiff works out of the box for me with the additional qt5 imageformats plugin (`qt5-imageformats` in arch linux). As @jcjgraf already found out, there seems to be a native qt plugin to support jp2 as well, but I am having difficulties to find more details on this :disappointed:
