### ISSUE TITLE
SVG Bad Scaling

### ISSUE THREAD

**Issue by gamefreq0** [karlch/vimiv-qt#423]
Opening an SVG file (at least, one generated by the Rust flamegraph program), it appears to be quite badly scaled.

Example output
![Badly scaled SVG output](https://user-images.githubusercontent.com/42497703/133650622-f45cefad-89cd-4704-9fea-57ce1443786e.png)

Desired output (using ImageMagick to convert the file to a png for this example)
![flamegraph](https://user-images.githubusercontent.com/42497703/133650983-06b10e47-ca00-4586-856f-3eb8122fc7e4.png)

The example SVG file used (GitHub doesn't support svg?)
[flamegraph.svg.gz](https://github.com/karlch/vimiv-qt/files/7179521/flamegraph.svg.gz)

Running vimiv circa commit a7a0b21dad54a6e1c161cc30d8d370bad0943b7f

Log: 
[vimiv.log](https://github.com/karlch/vimiv-qt/files/7179575/vimiv.log)

**Comment by karlch** [comment]
Thanks for the report!

I can reproduce this, but unfortunately also with other Qt-based image viewers (I tried [phototonic](https://github.com/oferkv/phototonic/) as it was available in the arch packages). This means there is probably not much we can do here, we could pass the bug on to Qt directly, or figure out if flame graph does something funky that is currently not supported. Other svg files I have tried so far work just fine.

**Comment by gamefreq0** [comment]
Oh, interesting; so it's probably an upstream issue with flamegraph and/or qtsvg?

**Comment by karlch** [comment]
Sorry for completely missing the question, shame on me.

I can reproduce the scaling issue with these few lines:
```python
from PyQt5.QtWidgets import QApplication
from PyQt5 import QtSvg


def main():
    app = QApplication([])
    widget = QtSvg.QSvgWidget("flamegraph.svg")
    widget.show()
    app.exec_()


if __name__ == "__main__":
    main()
```

I will probably not find the time to do a proper debug session to see if there is something we can do anytime soon unfortunately.

**Comment by karlch** [comment]
Closing as I still believe there is not much we can do. Issue persists using both `PyQt6` and  `PySide6`. Would have to be fixed upstream either with Qt for flamegraph.
