### ISSUE TITLE
Adding confirmation before deleting

### ISSUE THREAD

**Issue by timsofteng** [karlch/vimiv-qt#446]
Hello.
It would be nice to add promt with y/n options before file deleting.

**Comment by jcjgraf** [comment]
Hey @timsofteng, great that you are interested in using vimiv!

There is the command `:undelete` which restores the last deleted image. Also, the vimiv `:delete` command does not completely erase you image, but moves it into the system bin. So you can also manually get then back from there.

Let us know if this partially solves your issue

**Comment by timsofteng** [comment]
Thanks for quick reply.
For me confirmation in statusline before deleting feels way better.

**Comment by karlch** [comment]
I remember this coming up before, so I definitely see the value in this. Personally, I find it too noisy to be the default though. In #447 I have added a flag, so you could edit the behaviour of `x` in your `keys.conf` by adding the `--ask` flag. Would this solve the issue for you?

**Comment by timsofteng** [comment]
@karlch Sorry, I completely forget about this issue.
Could you tell me please how shoud I add this flag into config file?
