### ISSUE TITLE
Enable setting default scale level

### ISSUE THREAD

**Issue by adworacz** [karlch/vimiv-qt#509]
I'd love to be able to set the scale level to `fit` for every case. Especially when in slideshow mode.

It doesn't seem like it's currently possible to do this. Can a setting or keybinding be added to default the scaling to a desired level?

**Comment by jcjgraf** [comment]
Hey @adworacz. If I understand you currently setting `image.overzoom = Inf` should do what you want.
By default vimiv does fit images, but only as long as we do not need to "zoom in". This option specifies the maximal zoom which should be applied.

Let me know if that does not resolve your issue

**Comment by adworacz** [comment]
Yup, that did it!

A simple `vimiv -s image.overzoom Inf` worked like a charm. I've gone ahead and updated it in my conf file as well for permanence

**Comment by jcjgraf** [comment]
I am glad that I was able to help. If you do not have any follow-up questions you may close this issue

**Comment by adworacz** [comment]
Roger! Closing.
