### ISSUE TITLE
[Feature Request] Rename current file

### ISSUE THREAD

**Issue by mcp292** [karlch/vimiv-qt#517]
Please add an option to the `:rename` command that lets you rename the currently viewed file.

`:rename --current new_name.png`
`:rename --viewed new_name.png`

**Comment by jcjgraf** [comment]
Vimiv does not want to reinvent the wheel for such things. Use [external commands](https://karlch.github.io/vimiv-qt/documentation/getting_started.html#command-line) for such tasks. I.e. `:!mv % newImg.jpg`.

Possibly you could also create an alias for that, though I do not know of the top on my head how we handles arguments passed to aliases.

**Comment by mcp292** [comment]
Ah, yes! From your link:
> In addition % gets replaced with the currently selected file,
