### ISSUE TITLE
Was `--ask` removed from `delete`?

### ISSUE THREAD

**Issue by mcp292** [karlch/vimiv-qt#544]
The following binding:
```conf
[GLOBAL]
r : delete --ask %%
R : delete %%
```

results in an error:
```txt
delete: Unrecognized arguments: --ask
```

References:
https://github.com/karlch/vimiv-qt/issues/516#issuecomment-1183570871
#447

**Comment by jcjgraf** [comment]
Hi, no the option has not been removed. However, it is not included in the latest (and very dated) release. Which version of vimiv are you using? You should be using the latest git version.

**Comment by mcp292** [comment]
Ah, I am using `v0.8.0`. I will switch to the `vimiv-qt-git` AUR package and close this issue if that works.
