### ISSUE TITLE
How do I go to a specific directory (library) with a keybinding?

### ISSUE THREAD

**Issue by kohane27** [karlch/vimiv-qt#558]
Hello @karlch. Hope you're doing well. Thank you for creating this awesome vim-like image viewer.

I was surprised that the following doesn't work:

`keys.conf`:

```
gs : !cd ~/OneDrive/Documents/linux-screenshots/
gs : !spawn cd ~/OneDrive/Documents/linux-screenshots/
```

I've tried them both separately and resulted in `Error running 'cd': command notfoud or not executable`.

I go to some specific directories often and would like a keybinding to go to those directories directly, instead of selecting in the library every time.

I've looked into [Command Line](https://karlch.github.io/vimiv-qt/documentation/getting_started.html#command-line) and searched all issues but to no avail. 

Any help is much appreciated. Thank you!

**Comment by karlch** [comment]
Hi @kohane27 and happy new year! Thanks for your warm words :blush: 

In case you just want to open the path in the library, doesn't a simple
```
gs : open ~/OneDrive/Documents/linux-screenshots/
```
do the trick?

**Comment by kohane27** [comment]
Hello @karlch , thank you for looking into this GitHub issue of mine. I really appreciate it.

The `open` command is exactly what I need. Apologies. I didn't look hard enough.

For reference to future people, here's the relevant doc [Commands](https://karlch.github.io/vimiv-qt/documentation/commands.html#ref-global-open):

> Open one or more paths.
> syntax: :open path [path ...]

I have written a [blog post](https://devctrl.blog/posts/vimiv-to-substitute-for-rangers-image-preview-in-wayland/) about `vimiv`. Please check it out if you're interested. `vimiv` helps me a lot. Thank you again for this awesome project:)

**Comment by karlch** [comment]
Perfect, glad I could help! :blush: No worries, finding the correct part in the documentation can be tricky at times. Did you look for specific keywords we could add at that point, to make it easier to find in the future? Like `cd`?

Wow, thanks for the mention in the blog post!

**Comment by kohane27** [comment]
Hello @karlch  . Thank you for getting back to me.

I went through the whole [Getting Started](https://karlch.github.io/vimiv-qt/documentation/getting_started.html) part of the document. tbh it's just negligence on my part.

```
open Open one or more paths.
```

Adding keywords like `cd` and directories would be helpful, maybe something like:

```
open Open one or more paths (change directory of library).
```

Thank you again! I'm really really enjoying `vimiv`!

**Comment by karlch** [comment]
Perfect, I added a [quick hint](https://karlch.github.io/vimiv-qt/documentation/commands.html#ref-global-open) :blush:
