### ISSUE TITLE
Simplify Copyrights

### ISSUE THREAD

**Issue by karlch** [karlch/vimiv-qt#667]
It would make our life easier if we simplified the copyrights all over the place.

Code files I would use something along:
```
# Copyright: the vimiv contributors, licensed under the GNU GPL v3
# See the "AUTHORS" and "LICENSE" files for details
```

And then also use "the vimiv contributors" instead of "2017-2023, Christian Karl" for the sphinx-generated documents (website, man page).

This fulfils two purposes:
1. Remove the tedious bookkeeping of the years
2. Have all authors part of the copyright, not just me :smile: especially useful in case we move towards a vimiv organisation for v1.0.0.

**Comment by buzzingwires** [comment]
Not a lawyer, but I generally think the rationale behind this is great. Do you think a date should still be present in the copyright, though?

**Comment by karlch** [comment]
I've also seen the date used all over the place, which is why it is here in the first place, but stumbled upon [this article](https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects) by the linux foundation recommending something as simple as the above.

If we decide to keep the date, maybe we can only keep it in one place (AUTHORS file? sphinx?) and not in every single file :thinking:

**Comment by jcjgraf** [comment]
This is merely a design choice and has no legal implications, as the information in the header is redundant. Therefore, I support a simplification of the header.

I also support the movement to a vimiv organisation and adjusting the copyright statement for the vimiv organisation.

 We could go even as far as get completely rid of the header, as advocated by <headerless.org> (see their site for a list of advantages), and include the copyright (with or w/o) date in the *AUTHORS* file.

**Comment by buzzingwires** [comment]
I've done a little bit of reading on it, and it seems even some big companies are also moving away from copyright dates in their work, or headers altogether. So, it's probably a bit of legal cargo-cultism.

I think headerless with a copyright notice in the AUTHORS file would work nicely. Some projects are also adding a NOTICE file to the root of the repo with copyright information. Could do the initial date of publication in the copyright notice, as a compromise between continually updated dates, and no date at all.

**Comment by karlch** [comment]
Thank you two for your input! :blush: 

I think the solution of headerless + copyright in the AUTHORS file is really nice. I would probably not include the date at all then, as it somehow sounds to me as if everyone in the AUTHORS file worked on vimiv since then. No dates at all is simple and without confusion.

**Comment by jcjgraf** [comment]
From what I have seen, dates are often used when a project is forked or relicensed or changes owner/maintainer. I think there is really not need for a date in our case.
