### ISSUE TITLE
Consider an .editorconfig or somesuch for this project?

### ISSUE THREAD

**Issue by buzzingwires** [karlch/vimiv-qt#668]
Such an addition may be helpful by automatically specifying how indentation, linebreaks, and so on should be handled. I suggest .editorconfig as it is natively supported by a good number of editors, including Neovim natively, and Vim with a simple plugin.

**Comment by jcjgraf** [comment]
What else is there to specify except the indentation width? There is already a modeline in each file which specifies that. Though, I do not know how widely it is adopted.
In general, I am adverse to putting any editor-specific files (/headers) in a repo. Except if it is a widely supported standard.

But it is up to @karlch to descide.

**Comment by buzzingwires** [comment]
Hey, I owe everyone an apology. This was my fault. I had a setting that overrode the modeline setting, but not .editorconfig settings for some reason. That's on me and I'm sorry. Closing this issue.
