### ISSUE TITLE
Idea:  load styles on the fly

### ISSUE THREAD

**Issue by elig0n** [karlch/vimiv-qt#672]
it would be nice if we could switch styles on the fly
it might come especially useful for switching to/from "night theme"
it can be implemented for example with a command i.e. `:style filename` (without extension)

If not on the fly then a command line switch for styles will be appreciated as well
because otherwise loading a different theme requires manually editing the configuration file or maintaining two nearly-identical versions of them

**Comment by karlch** [comment]
Closing, as the proposed command line switch as workaround exists, and implementing it directly does seem more involved than the benefits :blush:
