### ISSUE TITLE
support avif image

### ISSUE THREAD

**Issue by elig0n** [karlch/vimiv-qt#673]
AVIF Image is not displayed with vimiv-qt v0.9.0

Python: 3.11.3
Qt: 5.15.8
PyQt: 5.15.9

Svg Support: True

**Comment by jcjgraf** [comment]
Vimiv supports `avif` using [imageformats plugin](https://karlch.github.io/vimiv-qt/documentation/configuration/plugins.html#imageformats). Let me know in case it still does not work, or if you have an idea on how to improve the documentation to prevent such confusion in the future.

**Comment by elig0n** [comment]
I managed to successfully install and employ the avif plugin following the documentation. 

I also got:

`ERROR    <imageformats>       Ignoring unknown image format 'jp2'`

but I could not find the "`jp2`" format mentioned in the [documentation](https://karlch.github.io/vimiv-qt/documentation/configuration/plugins.html#imageformats) anywhere in [imageformats.py](https://github.com/karlch/vimiv-qt/blob/master/vimiv/plugins/imageformats.py)

**Comment by jcjgraf** [comment]
I am glad that you manged to get it to work :+1: 

What you have spotted is an issue with the documentation. I also realized that yesterday and opened #674. Since #650, explicit enabling via the `imageformats` plugin is no longer required for `jp2`.
