### ISSUE TITLE
Switch to PyQt6 by default

### ISSUE THREAD

**Issue by karlch** [karlch/vimiv-qt#693]
After some further testing and running, it will make sense to switch to PyQt6 by default, instead of using PyQt5.

Now, I am unsure on the timing on this. It could make sense to do this before `0.10.0`, in another intermediate `0.11.0` (unfavoured, I guess) or directly on the way to `1.0.0`.

@jcjgraf, do you have an opinion on this?

**Comment by jcjgraf** [comment]
Versions are just numbers, so in the end it does not really matter 🙃 However, I would strive for making that switch rather sooner than later, such that more people use Qt6 and potentially report related bugs.
The release of `1.0.0` will probably take some time as there are a few other things that should be finished up before, I guess?. So maybe it would make sense to make the switch in `0.10.0` and create that release rather soon (this week?) :thinking:

**Comment by karlch** [comment]
Thanks for your thoughts! I agree with making the switch asap, and will prepare a PR tackling some of the remaining Qt6 issues opened over the past days including this then.

However, I am not sure it makes sense to rush the `0.10.0`, yet. We should definitely not take as long as the last one, that was pretty horrid of a schedule :laughing: but there is some more to do, and I would certainly like to run on Qt6 for a while before releasing with it.
