### ISSUE TITLE
plugins not visible

### ISSUE THREAD

**Issue by JosefLitos** [karlch/vimiv-qt#712]
I am trying to get supposedly named plugin `metadata_gexiv2` to work, but even when I try other plugins, or I try to rename the directories or the files to whatever, they don't even get registered by vimiv

**Comment by JosefLitos** [comment]
I discovered `XDG_DATA_HOME` corresponds to `~/.local/share/`, but I think there should be something that says this, my shell doesn't contain this variable, so I had to test every possible dotdir.

**Comment by jcjgraf** [comment]
Hi and thanks for reporting your issue. I hope you have managed to get the plugin to work as expected.

vimiv follows the [XDG standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). Therefore, we did not reiterate on that is said in the specifications.
However, I just saw that we mention the default location of `XDG_CONFIG_HOME` at several places in the docs(e.g. [here](https://github.com/karlch/vimiv-qt/blob/master/docs/documentation/configuration/settings.rst)), therefore we could also do it for `XDG_DATE_HOME`. Do you think that changes in #713 are sufficient to prevent similar confusion in the future?

**Comment by JosefLitos** [comment]
Most certainly yes, that would help a lot. I was originally not paying close enough attention to the `XDG_...` and therefore assumed all those dirs were just the `XDG_CONFIG_HOME` directory, I only later realized I was mistaken.

As a sidenote, Is there an option or already an existing script to make it so opening a directory with images immediately starts showing just the images - like `imv` does.

**Comment by jcjgraf** [comment]
Are you looking for `vimiv * --command "enter image"`?

**Comment by JosefLitos** [comment]
Yes indeed, thanks!
