### ISSUE TITLE
[feature request] add missing mime types to the desktop entry file

### ISSUE THREAD

**Issue by xlucn** [karlch/vimiv-qt#754]
In the `vimiv.desktop`, there are only a few image formats:
```
MimeType=image/bmp;image/gif;image/jpeg;image/jp2;image/jpeg2000;image/jpx;image/png;image/svg;image/tiff;
```
Some supported formats, e.g., `image/webp`, are missing from the list. As a result, vimiv won't be shown in the right-click menu or the recommended "open-with" list in GUI file managers. Adding those to the desktop entry file will be great.

**Comment by karlch** [comment]
Thanks a lot for opening this issue, makes perfect sense :blush: 

Would you like to add the missing (supported) formats yourself in a quick PR? Otherwise I'll try get it done over the week-end.

**Comment by xlucn** [comment]
Sorry, I don't know what exact image formats vimiv supports :(

**Comment by jcjgraf** [comment]
All supported types are actually really well listed up [here](https://github.com/karlch/vimiv-qt/blob/master/vimiv/utils/imageheader.py#L11C1-L25C85). The only question is whether to include only the natively supported ones, or also the ones that require `qtimageformats`.

**Comment by xlucn** [comment]
Thanks, @jcjgraf. I am preparing a PR and will commit soon.

As for the optionally supported formats, I will include them in the PR. If that's an issue, I think it can be mitigated by showing a in-program warning to install optional dependencies.
