### ISSUE TITLE
How to disable the scroll offsett in library and thumbnail view?

### ISSUE THREAD

**Issue by Markuzcha** [karlch/vimiv-qt#785]
...I can't find a setting for it.

In Library and Thumbnail view the currently selected file is always vertically centered. I want to be able to disable this scrolling offset.

Thank you for help.

My installation:
vimiv v0.9.0

Python: 3.11.7
Qt: 5.15.11
PyQt: 5.15.10

Svg Support: True

**Comment by karlch** [comment]
Thanks so much for your kind words! :blush: 

Your use-case makes perfect sense, never thought of that. I will add the setting, should be very straightforward.

I also think your keybindings make sense, please do open another issue for this, so we can keep the discussions separate. My hope is that these are also rather straightforward.

**Comment by karlch** [comment]
Nevermind with the extra issue, setting and view positioning has been implemented in #791 - do you think you could give this PR a shot? Otherwise I would happily just merge, and you can test from the git package.

**Comment by karlch** [comment]
Closing as #791 has been merged.
