### ISSUE TITLE
Cropping of images

### ISSUE THREAD

**Issue by karlch** [karlch/vimiv-qt#8]
A nice widget to crop images without the use of external commands would be nice to have.

See [this issue of the GTK version](https://github.com/karlch/vimiv/issues/54).

**Comment by eorus** [comment]
I enjoy using Vimiv and as a photographer, Darktable and Gimp do my job in extensive editing needs. On the other hand, for simple editing, I use cropping and compression with the -resize or -quality parameters with the "convert" command in the terminal. 

For this improvement, if we can give simple Imagemagick commands via Vimiv :!convert parameters, we can manage many simple editing operations visually. Or a shell command like Ranger might work.

**Comment by karlch** [comment]
Calling shell commands should absolutely be possible, I am just not sure how well this works in case you actualy would like to select a crop region.

Have you tried something along:
```
:!convert -whatever -arguments -you -need % output.jpg
```
Note that `%` is expanded to the name of the current file. Some more information [is available in the command line documentation](https://karlch.github.io/vimiv-qt/documentation/getting_started.html#command-line).

If you require an actual sub-shell, e.g. for pipes, use `:spawn` instead of `:!`.

What I would like here is an actual crop widget which you can drag, resize and so forth in the UI. So basically this, just without the remaining bugs :smile:

![scrot-2020-04-22_12:37:33](https://user-images.githubusercontent.com/12006766/79972519-5c7edc00-8496-11ea-987c-cd60fe301fdf.png)

**Comment by eorus** [comment]
On my first attempt, I skipped putting output.jpg to the end. So I got an error. I thought I would overwrite the same file and also forgot to put % i guess.

Now it simply meets my request when I run it as follows. It will be very useful for me as there are numerous options available with "convert". Still, if the crop widget feature you specified is added, it is a good improvement.

With this little advice, you made an important addition to the program for me. :) In Vimiv documents, it would be good to state that :!convert command can be used. I hope it will be useful for others.

Thanks for taking time for quick replies. 
Best.

**Comment by karlch** [comment]
If I remember imagemagick correctly, you would overwrite the same file using `mogrify` instead of `convert`, so your command would read:
```
:!mogrify -resize 900 -quality 75 %
```

I am not quite sure how you would update the documentation, just add more examples with convert like the one covering gimp? If you like, you could also add some examples useful to you to `docs/documentation/getting_started.rst` in the form of:
```
Examples:

* ``:!gimp %`` opens the currently selected image in gimp.
* ``:!convert % -option -other output.jpg`` does something with the current image and
  saves it to ``output.jpg``.
```
and open a PR :)

**Comment by karlch** [comment]
While the actual crop widget is definitely out of scope for the time being, as our manpower is quite limited and there are quite some other things to work on first (c.f. #560), a simple statusbar module *could* be quick enough to fit in :blush: 

I did a very rough first implementation in the [cursor-position](https://github.com/karlch/vimiv-qt/tree/cursor-position) branch. To show the coordinates, one has to add the `{cursor-position}` module to the statusbar [as usual](https://karlch.github.io/vimiv-qt/documentation/configuration/statusbar.html), e.g. just in image mode. @Yutsuten do you think you could give this a quick test if it already helps? Just let me know if you need additional help running this. I would then probably do some cleaning and merge it in :blush:

Concerning the actual crop widget, a lot of work happened (3 years ago :joy:) in the [crop](https://github.com/karlch/vimiv-qt/tree/crop) branch, but this never quite made it in due to some bugs in corner-cases. I do not recall what these were exactly, but suspect crop + zoom not playing well in the old state. If someone would like to pick this up, stabilize the issues, and open a PR, this would of course have a much larger chance of getting in :blush:

**Comment by Yutsuten** [comment]
Oh nice @karlch , I'll take a look at that for sure!!

**Comment by Yutsuten** [comment]
I tested it here! It is exactly what I was thinking about!! :+1:

**Comment by karlch** [comment]
Thanks for the quick test, at least the statusbar module is merged into master :partying_face:

**Comment by karlch** [comment]
> It is hard to make promises as I'm very busy too, but I can give it a try!

That would be really helpful, but don't feel pressured of course, only if you have the time! :blush: What could already help is rebasing the old branch onto the current master and giving it a detailed test, noting down what the issues are / how the user feel is, as a starting point.
