### ISSUE TITLE
In the style config library.selected.fg directive has no effect

### ISSUE THREAD

**Issue by favinator** [karlch/vimiv-qt#840]
I noticed that the directive `library.selected.fg ` does nothing.
I changed both `library.selected.fg ` and `library.selected.bg ` but it only changed the background.
Here is a screenshot of what I'm trying to explain in my poor english...

![bugvimiv](https://github.com/karlch/vimiv-qt/assets/156591969/a01c2342-5a20-4088-87b7-114768557241)

**Comment by karlch** [comment]
Thanks a bunch for catching this and reporting the issue! I can reproduce it and also know where this is coming from. Hoping to push a fix sometime this week :blush: 

For the curious: we use a delegate to paint the library within `vimiv/gui/library.py`, but the delegate does not differ between foreground colors for selected / non-selected rows. Clearly a bug, as it does correctly differ for backgrounds.

[Code for font color](https://github.com/karlch/vimiv-qt/blob/master/vimiv/gui/library.py#L581) vs [code for bg color](https://github.com/karlch/vimiv-qt/blob/master/vimiv/gui/library.py#L595).

**Comment by karlch** [comment]
Should be fixed with #843, thanks again for reporting :blush:
