### ISSUE TITLE
Unable to bind semicolon

### ISSUE THREAD

**Issue by sheitfugit** [karlch/vimiv-qt#845]
Pretty self-explanatory. In the binds, neither `<semicolon>` nor `;` works to bind semicolon to a key, which is a problem for someone that tends to use jkl; instead of hjkl in vim-like layouts.

**Comment by karlch** [comment]
Thanks a bunch for reporting!

And as @qadzek has mentioned, this was indeed due to configparser interpreting ; (and #) as a comment symbol, thus the line was not read at all. Should be fixed with the recent merge by explicitly re-mapping them to `<semicolon>` and `<number>` respectively :blush:
