### ISSUE TITLE
Use girara (zathura's user interface library)?

### ISSUE THREAD

**Issue by sanjayankur31** [karlch/vimiv-qt#91]
Hiya,

I was looking into some zathura bugs and learned that they use a library called girara for their UI. It seems to implement the vim like interface already, so maybe that's worth looking into? That way, you needn't write all of that part yourself? :thinking: 

https://git.pwmt.org/pwmt/girara

**Comment by karlch** [comment]
Hey, thanks for your suggestion and sorry for the rather late reply (I was on holiday).

As far as I can see this would require
* writing vimiv in C or possibly C++, I couldn't find any python bindings on the fly
* switching back to Gtk

Especially the programming language is a complete show-stopper for me as my C skills are rather limited. I also came to like qt and its python support. Please correct me if I am wrong, I only had a very quick look at girara.

**Comment by sanjayankur31** [comment]
Yeh, I haven't been able to find any Python bindings either, and yes, it does look like it's built on top of GTK. You're right---it doesn't quite fit vimiv's requirements. Closing :slightly_smiling_face:
